[platformio]
default_envs = nano_33_iot
test_dir = test

[env:nano_33_iot]
platform = atmelsam
board = nano_33_iot
framework = arduino
build_src_filter = +<*>
build_flags = -Iinclude

[env:native_test]
platform = native
test_framework = unity
test_filter = test_main
test_build_src = true

build_src_filter =
    +<*>
    +<../test/stubs/Arduino.cpp>
    +<../test/stubs/power_monitor_stub.cpp>
    -<power_monitor.cpp>
    -<main.cpp>
    -<system.cpp>

build_flags =
    -std=c++11
    -DNATIVE_TEST
    -Iinclude
    -Itest/stubs


; $pio = "$env:USERPROFILE\.platformio\penv\Scripts\platformio.exe"

; if (Test-Path $pio) {
;   & $pio run -t clean -e native_test 
;   & $pio test -e native_test -vv
; } else {
;   py -m pip install -U platformio
;   py -m platformio run -t clean -e native_test
;   py -m platformio test -e native_test -vv
; }